### ISSUE TITLE
Question : Any plan for a parser ? 

### ISSUE THREAD

**Issue by isatahiri** [enioag/iso20022-generator#3]
Hi ! 
This code is very cool and useful. Can't wait to test it in my project. 
Do you have a plan de release a parser too for the incoming payments ? 

Thanks for your response. 
BR
ISA

**Comment by ruffzy** [comment]
Hi Isa, great if you can use the code! Unfortunately we don't have any plans to implement additional interfaces at the moment. We just go on with programming if we need this code in one of our projects. But if you can't find any existing code please feel free to take part on this project.
regards, marco
